### ISSUE TITLE
make command fails on KDE Neon qt6

### ISSUE THREAD

**Issue by stefonarch** [lxqt/libdbusmenu-lxqt#6]
Package "doxygen" is needed for make but is not checked for.

**Comment by tsujan** [comment]
It is checked: https://github.com/lxqt/libdbusmenu-lxqt/blob/7cc060cfc366cd52cce373be8ba852c4ef6b8cf5/CMakeLists.txt#L6

**Comment by stefonarch** [comment]
Maybe a new issue is needed but building this blocked now already 4 times completely different VMs.
