### ISSUE TITLE
App menus on Qt6 not working

### ISSUE THREAD

**Issue by stefonarch** [lxqt/libdbusmenu-lxqt#9]
No interaction can be done with applications shown in statusnotifier in all Qt6 branches.
Built the panel with `libdbusmenu-qt6`, same result.

**Comment by tsujan** [comment]
Why reporting it here?

**Comment by stefonarch** [comment]
Indeed wasn't sure if it's a problem with the plugin or with this. Do you think it's a statusnotifier plugin issue?

**Comment by tsujan** [comment]
I think that's more probable because, if I correctly remember, libdbusmenu-lxqt also enables tray menus of Qt6 apps under other trays, and we know that, for example, there's no problem with Waybar.

**Comment by stefonarch** [comment]
`Error on DBus request(:1.1084,/StatusNotifierItem): QDBusError(org.freedesktop.DBus.Error.Failed, error occurred in Get)`

In journalctl or starting the panel this error shows up twice. A change in QDbus?
https://doc.qt.io/qt-6/dbus-changes-qt6.html
